### ISSUE TITLE
Pagina de produse: Nu afiseaza corect produsele

### ISSUE THREAD

**Issue by cipiut** [SoucupB/SiteApp#14]
Ar trebui sa lasam doar 16 produse pe pagina de produse, afisate sub forma unei matrice 4x4. 
Daca lasam 4x4 trebuie sa setam  sa se faca paginarea cu 16 produse nu cu 15.
![image](https://user-images.githubusercontent.com/43930035/103182491-50b0a880-48b4-11eb-9e24-03d0a0a72bef.png)

**Comment by SoucupB** [comment]
.done
![image](https://user-images.githubusercontent.com/49458226/103326627-f18c9880-4a59-11eb-9cec-b5ab2be5c709.png)
