### ISSUE TITLE
Pagina de produse: Filtre afisate incorect

### ISSUE THREAD

**Issue by cipiut** [SoucupB/SiteApp#15]
cand nu aplicam nici un filtru, merge bine. dar cand aplicam un filtru care scurteaza pagina, nu se mai vad filtrele 
![image](https://user-images.githubusercontent.com/43930035/103182518-8786be80-48b4-11eb-8be2-bebf733d8602.png)
Poza 1 arata ca atunci cand nu e nici un filtru setat totu arata ok
![image](https://user-images.githubusercontent.com/43930035/103182524-97060780-48b4-11eb-9180-b4017900632f.png)
Poza 2 arata ca nu se mai vad filtrele de dupa "multicolor"... pur si simplu nu mai putem selecta acele filtre

**Comment by SoucupB** [comment]
.done for now
![image](https://user-images.githubusercontent.com/49458226/103325706-a1133c00-4a55-11eb-9431-739eb3ea62d8.png)
![image](https://user-images.githubusercontent.com/49458226/103325713-aa9ca400-4a55-11eb-8add-69c4f1f76c0a.png)
![image](https://user-images.githubusercontent.com/49458226/103325997-0287da80-4a57-11eb-9b43-64d6f08f0c4b.png)
