### ISSUE TITLE
Pagina de produse: Filtre pentru categorie

### ISSUE THREAD

**Issue by cipiut** [SoucupB/SiteApp#16]
Ar trebuii sa punem niste filtre pentru categorie. (Tipu placi) 
Asa trebuie sa arate. Exact ca la colecti. La fel se fac filtrarile si acolo ;)
![image](https://user-images.githubusercontent.com/43930035/103182653-d5e88d00-48b5-11eb-8394-84be14009420.png)

**Comment by cipiut** [comment]
Poza e photoshop de proasta calitate :))) nu am implementat nimic 👍

**Comment by SoucupB** [comment]
Asta nu ar trebui sa ramane la alea din stanga pentru consistenta? Nu de alta da ar fi ciudat sa ai filtre in mai multe parti de pe pagina

**Comment by SoucupB** [comment]
![image](https://user-images.githubusercontent.com/49458226/103255691-f4708600-4992-11eb-8328-fb95a73807ec.png)
![image](https://user-images.githubusercontent.com/49458226/103255700-fb979400-4992-11eb-8e04-545ee1265b6c.png)
