### ISSUE TITLE
Colectie: Slideshow-ul cu imaginile de prezentare

### ISSUE THREAD

**Issue by cipiut** [SoucupB/SiteApp#18]
Slideshow-ul cu imaginile de prezentare nu este afisat la o anumita marime. 
Ar trebui dat resize la slideshow astfel incat sa fie constant. 
Pentru unele imagini e mai mare pentru altele e mai mic. 
Trebuie setata la o dimensiune anume, dupa vedem noi care e cea mai acceptabila dimensiune. (700x350 pare dimensiunea perfecta)

**Comment by SoucupB** [comment]
.closing
