### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by cipiut** [SoucupB/SiteApp#19]
Trebuie sa punem acel api de map ca sa facem pinuri pe google maps la locatiile pe care le are Impexcera Lux.
Bucuresti, Cluj-Napoca, Cristesti

**Comment by SoucupB** [comment]
.done
![image](https://user-images.githubusercontent.com/49458226/103377667-aff6fe80-4ae8-11eb-8a3f-60270667bfc3.png)
![image](https://user-images.githubusercontent.com/49458226/103377677-bab19380-4ae8-11eb-945a-08c11adb1dcf.png)
![image](https://user-images.githubusercontent.com/49458226/103377696-c735ec00-4ae8-11eb-8f81-22b257da3c75.png)
